#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
fi

# Create symlink to custom_components in config directory if it doesn't exist
if [[ ! -L "${PWD}/config/custom_components" ]]; then
    ln -sf "${PWD}/custom_components" "${PWD}/config/custom_components"
fi

# Start Home Assistant
hass --config "${PWD}/config" --debug
